_POSITION_DIM = "position"
_POSITION_COORDS = ["x", "y", "z"]
_POSITION_COORD_DICT = {_POSITION_DIM: _POSITION_COORDS}
_QUATERNION_DIM = "quaternion"
_QUATERNION_COORDS = ["x", "y", "z", "w"]
_QUATERNION_COORD_DICT = {_QUATERNION_DIM: _QUATERNION_COORDS}
